### ISSUE TITLE
Can not parse cookies crorrectly

### ISSUE THREAD

**Issue by crazyjin** [nahi/httpclient#246] opened 2015-02-28 11:03 UTC
If a http response header contains the following line:
```
Set-Cookie: ticket="abcdefg"
```
The value of cookie ticket will be parsed as "abcdefg", actually, it should be "\"abcdefg\"".

**Comment by nahi** [comment] 2015-03-09 12:34
It's difficult issue... I take this as a duplicate of #145. Closing but let me know if I'm misunderstanding.

**Closed by nahi** 2015-03-09 12:34 UTC
